//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStock()
        {
            this.tblCustomerInvoiceDetails = new HashSet<tblCustomerInvoiceDetail>();
            this.tblCustomerReturnInvoiceDetails = new HashSet<tblCustomerReturnInvoiceDetail>();
            this.tblPurchaseCartDetails = new HashSet<tblPurchaseCartDetail>();
            this.tblSaleCartDetails = new HashSet<tblSaleCartDetail>();
            this.tblSaleCartDetails1 = new HashSet<tblSaleCartDetail>();
            this.tblSupplierInvoiceDetails = new HashSet<tblSupplierInvoiceDetail>();
            this.tblSupplierReturnInvoiceDetails = new HashSet<tblSupplierReturnInvoiceDetail>();
        }

        public int ProductID { get; set; }
        [Required(ErrorMessage = "*Required!")]
        public int CategoryID { get; set; }
        public int CompanyID { get; set; }
        public int BranchID { get; set; }
        [Required(ErrorMessage = "*Required!")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "*Required!")]
        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1")]
        public int Quantity { get; set; }
        [Required(ErrorMessage = "*Required!")]
        [Range(1, int.MaxValue, ErrorMessage = "Sale Price should be more than 0.00")]
        public double SaleUnitPrice { get; set; }
        [Required(ErrorMessage = "*Required!")]
        [Range(1, int.MaxValue, ErrorMessage = "Current Purchase Price should be more than 0.00")]
        public double CurrentPurchaseUnitPrice { get; set; }
        [Required(ErrorMessage = "*Required!")]
        [DataType(DataType.Date)]
        public System.DateTime ExpiryDate { get; set; }
        [Required(ErrorMessage = "*Required!")]
        [DataType(DataType.Date)]
        public System.DateTime Manufacture { get; set; }
        [Required(ErrorMessage = "*Required!")]
        public int StockTreshHoldQuantity { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public int UserID { get; set; }
        [Required(ErrorMessage = "*Required!")]
        public bool IsActive { get; set; }

        public virtual tblBranch tblBranch { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerInvoiceDetail> tblCustomerInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerReturnInvoiceDetail> tblCustomerReturnInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseCartDetail> tblPurchaseCartDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleCartDetail> tblSaleCartDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleCartDetail> tblSaleCartDetails1 { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupplierInvoiceDetail> tblSupplierInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupplierReturnInvoiceDetail> tblSupplierReturnInvoiceDetails { get; set; }
    }
}
